### ISSUE TITLE
Bug: add "_composer" query only where there are no services

### ISSUE THREAD

**Issue by simone-sanfratello** [platformatic/graphql-composer#42]

**Comment by simone-sanfratello** [comment]
The composer doesn't have any resolver, only the merged entity types so the `_composer` is needed
Can be used to get information about the composer

wdyt @mcollina?

**Comment by mcollina** [comment]
Can you clarify? I don't understand

**Comment by simone-sanfratello** [comment]
Using `addEntitiesResolvers` option, the composer automatically creates a new subgraph node to fill the entity types, based on the entities options, for example

```gql
type Artist { id: ID, movies: [Movie], songs: [Song] }
type Movie { id: ID!, director: Artist, cinemas: [Cinema] }
type Song { id: ID!, singer: Artist }
type Cinema { id: ID!, movies: [Movie] }
```

But it doesn't create any resolver, routing the subquery to the subgraph entity 

gql doesn't allow to create a service without any Query resolver (afaik), so I've put the

**Comment by mcollina** [comment]
SGTM
